describe('companyDetails',()=>{
    beforeEach(()=>{
        cy.visit('https://onboarding-rps.hs-staging.com/en/register')
    })
    it('Use EN name for AR field', ()=>{
      cy.xpath('//*[@id="companyFormValidate"]/div/div[1]/label').click()
      cy.xpath('//*[@id="company_name_ar"]').type('TestName')
     cy.xpath('//*[@id="company_name_ar-error"]')
     .should('have.css','color','rgb(255, 95, 79)')
    .contains('Please enter the name in Arabic letters')
    })
    it('Use numbers for AR field', ()=>{
      cy.xpath('//*[@id="companyFormValidate"]/div/div[1]/label').click()
      cy.xpath('//*[@id="company_name_ar"]').type('45633')
     cy.xpath('//*[@id="company_name_ar-error"]')
     .should('have.css','color','rgb(255, 95, 79)')
    .contains('Please enter the name in Arabic letters')
    })
    it('Use spaces for AR field', ()=>{
      cy.xpath('//*[@id="companyFormValidate"]/div/div[1]/label').click()
      cy.xpath('//*[@id="company_name_ar"]').type('             ')
     cy.xpath('//*[@id="company_name_ar-error"]')
     .should('have.css','color','rgb(255, 95, 79)')
    .contains('Please enter the name in Arabic letters')
    })
    it('Empty AR Field', ()=>{
      cy.xpath('//*[@id="companyFormValidate"]/div/div[1]/label').click()
      cy.xpath('//*[@id="company_name_ar"]').click().type('TestName')
      .type('Test').clear()
      cy.xpath('//*[@id="company_name_ar-error"]')
      .should('have.css','color','rgb(255, 95, 79)')
    .contains('required')
    })
    it('Use ar name for EN field', ()=>{
      cy.xpath('//*[@id="companyFormValidate"]/div/div[2]/label').click()
      cy.xpath('//*[@id="company_name_en"]').type('تيست')
     cy.xpath('//*[@id="company_name_en-error"]')
     .should('have.css','color','rgb(255, 95, 79)')
    .contains('Please enter the name in English letters')
    })
    it('Empty EN Field', ()=>{
      cy.xpath('//*[@id="companyFormValidate"]/div/div[1]/label').click()
      cy.xpath('//*[@id="company_name_en"]').click() .type('Test').clear()
      cy.xpath('//*[@id="company_name_en-error"]')
      .should('have.css','color','rgb(255, 95, 79)')
    .contains('required')
    })
    it('Saudi CR less than 3 digits', ()=>{
      cy.xpath('//*[@id="company_field"]/div[2]/div/div[1]/label').click()
      cy.xpath('//*[@id="cr_num"]').click()
      .type('12')
      cy.xpath('//*[@id="cr_num-error"]')
      .should('have.css','color','rgb(255, 95, 79)')
    .contains('Please enter a correct commercial registration')
    })
   it('Saudi CR exceed 10 digits', ()=>{
    cy.xpath('//*[@id="company_field"]/div[2]/div/div[1]/label').click()
    cy.xpath('//*[@id="cr_num"]').click()
    .type('12345678900')
    cy.xpath('//*[@id="cr_num-error"]')
    .should('have.css','color','rgb(255, 95, 79)')
  .contains('Please enter a correct commercial registration')
    })
    it('CR number as charcter', ()=>{
      cy.xpath('//*[@id="company_field"]/div[2]/div/div[1]/label').click()
      cy.xpath('//*[@id="cr_num"]').click()
      .type('hhhhhhh')
      cy.xpath('//*[@id="cr_num-error"]')
      .should('have.css','color','rgb(255, 95, 79)')
    .contains('Please enter a correct commercial registration')
      })
    it('Empty CR field', ()=>{
      cy.xpath('//*[@id="cr_num"]').click()
      .type('12345678900').clear()
      cy.xpath('//*[@id="cr_num-error"]')
      .should('have.css','color','rgb(255, 95, 79)')
    .contains('required')
    })
    it('Submit Company Info',()=>{
      cy.xpath('//*[@id="companyFormValidate"]/div/div[1]/label').click()
      cy.xpath('//*[@id="company_name_ar"]').type('تست')
      cy.get('#companyFormValidate > .form_container > :nth-child(2)').click()
      cy.xpath('//*[@id="company_name_en"]').type('TestName')
      cy.xpath('//*[@id="company_field"]/div[2]/div/div[1]/label').click()
    cy.xpath('//*[@id="cr_num"]').click()
    .type('1234567890')
    cy.xpath('//*[@id="nextBtn"]').should('have.css','color','rgb(0, 0, 0)')
    })
  })